### ISSUE TITLE
Crash on process death in basic example

### ISSUE THREAD

**Issue by Zhuinden** [lbenedetto/Shank#1]
```
--------- beginning of crash
11-26 22:39:48.613 4264-4264/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lbenedetto.basicshankexample, PID: 4264
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lbenedetto.basicshankexample/com.lbenedetto.basicshankexample.test.TestActivity}: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: kotlin.KotlinNullPointerException
        at com.lbenedetto.shank.ShankPresenter$Companion.bind(ShankPresenter.kt:21)
        at com.lbenedetto.shank.ConstructableActivity.setView(ConstructableActivity.kt:19)
        at com.lbenedetto.basicshankexample.test.TestActivity.onCreate(TestActivity.kt:12)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by lbenedetto** [comment]
Thanks. 
I am aware of the issue, and am working on it.
